# Site settings
title: Howard's Blog
email: althoughghgh@gmail.com
description: > #
  A passionate Ruby developer and a dad with excellent parenting skills.
baseurl: ""
url: "http://although2013.github.io"
# twitter_username: althoughcc
github_username:  although2013

# Build settings
markdown: Kramdown
