# Site settings
title: Howard's Blog
email: althoughghgh@gmail.com
description: > #
  I never did a day's work in my life, it was all fun. -- Thomas A. Edison
baseurl: ""
url: "http://blog.although2013.com"
twitter_username: although13
github_username:  although2013

# Build settings
markdown: Redcarpet
