# Site settings
title: Howard's Blog
email: althoughghgh@gmail.com
description: > #
  I sometimes wish I'd never been born at all.
baseurl: ""
url: "http://although2013.com"
twitter_username: althoughcc
github_username:  although2013

# Build settings
markdown: Kramdown
